X try to optimize fsrefs memory usage + debug
On 73GB database in question

- [info] FileStorage._index uses ~ 700MB of RAM.

- use QQBTree instead of [](pos,oid) for pos -> oid index.
  The list was using ~ 10GB of RAM, QQBTree uses ~ 2GB.
- don't remember ref's klass in the graph
- use QSet<oid> for refs in the graph

This lowers RAM consumption from ~28GB (https://github.com/zopefoundation/ZODB/pull/338#issuecomment-804539929)
to ~15GB, but still it is too much.

I will retry with the second version of the patch that preserves
2-passes approach instead of building in-memory graph, and only changes
iteration from oid-ordered to pos-ordered.

    [0.0s]  start:  VIRT: 160 MB    RSS: 20MB
    [2.2s]  open:   VIRT: 816 MB    RSS: 675MB
    # building pos2oid index ...
    [82.4s] pos2oid:        VIRT: 3074 MB   RSS: 2933MB
    # building references graph ...
    [114.2s]        1000000 / 85814607 (0.0 %):     VIRT: 3226 MB   RSS: 3086MB
    [145.7s]        2000000 / 85814607 (0.0 %):     VIRT: 3387 MB   RSS: 3247MB
    [178.9s]        3000000 / 85814607 (0.0 %):     VIRT: 3547 MB   RSS: 3406MB
    [214.4s]        4000000 / 85814607 (0.0 %):     VIRT: 3729 MB   RSS: 3589MB
    [248.4s]        5000000 / 85814607 (0.1 %):     VIRT: 3894 MB   RSS: 3753MB
    [281.0s]        6000000 / 85814607 (0.1 %):     VIRT: 4069 MB   RSS: 3929MB
    [314.6s]        7000000 / 85814607 (0.1 %):     VIRT: 4239 MB   RSS: 4098MB
    [349.8s]        8000000 / 85814607 (0.1 %):     VIRT: 4411 MB   RSS: 4270MB
    [383.2s]        9000000 / 85814607 (0.1 %):     VIRT: 4599 MB   RSS: 4459MB
    [418.1s]        10000000 / 85814607 (0.1 %):    VIRT: 4757 MB   RSS: 4616MB
    [452.6s]        11000000 / 85814607 (0.1 %):    VIRT: 4915 MB   RSS: 4775MB
    [485.5s]        12000000 / 85814607 (0.1 %):    VIRT: 5076 MB   RSS: 4935MB
    [518.7s]        13000000 / 85814607 (0.2 %):    VIRT: 5240 MB   RSS: 5099MB
    [553.5s]        14000000 / 85814607 (0.2 %):    VIRT: 5405 MB   RSS: 5264MB
    [588.0s]        15000000 / 85814607 (0.2 %):    VIRT: 5572 MB   RSS: 5431MB
    [620.3s]        16000000 / 85814607 (0.2 %):    VIRT: 5715 MB   RSS: 5574MB
    [652.6s]        17000000 / 85814607 (0.2 %):    VIRT: 5871 MB   RSS: 5731MB
    [686.9s]        18000000 / 85814607 (0.2 %):    VIRT: 6013 MB   RSS: 5872MB
    [720.8s]        19000000 / 85814607 (0.2 %):    VIRT: 6154 MB   RSS: 6013MB
    [754.5s]        20000000 / 85814607 (0.2 %):    VIRT: 6294 MB   RSS: 6153MB
    [787.3s]        21000000 / 85814607 (0.2 %):    VIRT: 6434 MB   RSS: 6293MB
    [826.7s]        22000000 / 85814607 (0.3 %):    VIRT: 6635 MB   RSS: 6495MB
    [863.5s]        23000000 / 85814607 (0.3 %):    VIRT: 6779 MB   RSS: 6639MB
    [896.0s]        24000000 / 85814607 (0.3 %):    VIRT: 6923 MB   RSS: 6782MB
    [929.1s]        25000000 / 85814607 (0.3 %):    VIRT: 7067 MB   RSS: 6926MB
    [962.1s]        26000000 / 85814607 (0.3 %):    VIRT: 7208 MB   RSS: 7067MB
    [996.3s]        27000000 / 85814607 (0.3 %):    VIRT: 7354 MB   RSS: 7213MB
    [1030.1s]       28000000 / 85814607 (0.3 %):    VIRT: 7503 MB   RSS: 7362MB
    [1065.1s]       29000000 / 85814607 (0.3 %):    VIRT: 7657 MB   RSS: 7516MB
    [1103.1s]       30000000 / 85814607 (0.3 %):    VIRT: 7803 MB   RSS: 7662MB
    [1135.4s]       31000000 / 85814607 (0.4 %):    VIRT: 7950 MB   RSS: 7809MB
    [1167.6s]       32000000 / 85814607 (0.4 %):    VIRT: 8095 MB   RSS: 7955MB
    [1201.0s]       33000000 / 85814607 (0.4 %):    VIRT: 8253 MB   RSS: 8112MB
    [1233.3s]       34000000 / 85814607 (0.4 %):    VIRT: 8400 MB   RSS: 8259MB
    [1265.7s]       35000000 / 85814607 (0.4 %):    VIRT: 8547 MB   RSS: 8406MB
    [1298.8s]       36000000 / 85814607 (0.4 %):    VIRT: 8690 MB   RSS: 8550MB
    [1331.2s]       37000000 / 85814607 (0.4 %):    VIRT: 8837 MB   RSS: 8697MB
    [1363.7s]       38000000 / 85814607 (0.4 %):    VIRT: 8986 MB   RSS: 8845MB
    [1401.0s]       39000000 / 85814607 (0.5 %):    VIRT: 9133 MB   RSS: 8992MB
    [1433.7s]       40000000 / 85814607 (0.5 %):    VIRT: 9280 MB   RSS: 9140MB
    [1466.0s]       41000000 / 85814607 (0.5 %):    VIRT: 9428 MB   RSS: 9287MB
    [1507.4s]       42000000 / 85814607 (0.5 %):    VIRT: 9614 MB   RSS: 9474MB
    [1556.7s]       43000000 / 85814607 (0.5 %):    VIRT: 9795 MB   RSS: 9654MB
    [1595.7s]       44000000 / 85814607 (0.5 %):    VIRT: 9981 MB   RSS: 9840MB
    [1631.0s]       45000000 / 85814607 (0.5 %):    VIRT: 10133 MB  RSS: 9992MB
    [1670.4s]       46000000 / 85814607 (0.5 %):    VIRT: 10322 MB  RSS: 10181MB
    [1704.2s]       47000000 / 85814607 (0.5 %):    VIRT: 10476 MB  RSS: 10335MB
    [1743.2s]       48000000 / 85814607 (0.6 %):    VIRT: 10629 MB  RSS: 10488MB
    [1777.3s]       49000000 / 85814607 (0.6 %):    VIRT: 10789 MB  RSS: 10648MB
    [1811.8s]       50000000 / 85814607 (0.6 %):    VIRT: 10944 MB  RSS: 10804MB
    [1848.1s]       51000000 / 85814607 (0.6 %):    VIRT: 11137 MB  RSS: 10996MB
    [1881.5s]       52000000 / 85814607 (0.6 %):    VIRT: 11292 MB  RSS: 11152MB
    [1917.5s]       53000000 / 85814607 (0.6 %):    VIRT: 11447 MB  RSS: 11306MB
    [1950.3s]       54000000 / 85814607 (0.6 %):    VIRT: 11602 MB  RSS: 11461MB
    [1983.6s]       55000000 / 85814607 (0.6 %):    VIRT: 11758 MB  RSS: 11617MB
    [2017.4s]       56000000 / 85814607 (0.7 %):    VIRT: 11916 MB  RSS: 11775MB
    [2051.6s]       57000000 / 85814607 (0.7 %):    VIRT: 12073 MB  RSS: 11932MB
    [2087.2s]       58000000 / 85814607 (0.7 %):    VIRT: 12230 MB  RSS: 12089MB
    [2120.6s]       59000000 / 85814607 (0.7 %):    VIRT: 12387 MB  RSS: 12246MB
    [2154.6s]       60000000 / 85814607 (0.7 %):    VIRT: 12544 MB  RSS: 12403MB
    [2196.0s]       61000000 / 85814607 (0.7 %):    VIRT: 12700 MB  RSS: 12559MB
    [2231.1s]       62000000 / 85814607 (0.7 %):    VIRT: 12856 MB  RSS: 12715MB
    [2266.3s]       63000000 / 85814607 (0.7 %):    VIRT: 13051 MB  RSS: 12910MB
    [2301.9s]       64000000 / 85814607 (0.7 %):    VIRT: 13197 MB  RSS: 13056MB
    [2335.1s]       65000000 / 85814607 (0.8 %):    VIRT: 13347 MB  RSS: 13207MB
    [2368.1s]       66000000 / 85814607 (0.8 %):    VIRT: 13503 MB  RSS: 13362MB
    [2403.2s]       67000000 / 85814607 (0.8 %):    VIRT: 13662 MB  RSS: 13521MB
    [2436.8s]       68000000 / 85814607 (0.8 %):    VIRT: 13815 MB  RSS: 13674MB
    [2469.6s]       69000000 / 85814607 (0.8 %):    VIRT: 13967 MB  RSS: 13826MB
    [2503.5s]       70000000 / 85814607 (0.8 %):    VIRT: 14123 MB  RSS: 13982MB
    [2536.8s]       71000000 / 85814607 (0.8 %):    VIRT: 14275 MB  RSS: 14135MB
    [2570.4s]       72000000 / 85814607 (0.8 %):    VIRT: 14427 MB  RSS: 14286MB
    [2604.9s]       73000000 / 85814607 (0.9 %):    VIRT: 14584 MB  RSS: 14444MB
    [2638.8s]       74000000 / 85814607 (0.9 %):    VIRT: 14740 MB  RSS: 14599MB
    [2672.6s]       75000000 / 85814607 (0.9 %):    VIRT: 14899 MB  RSS: 14758MB
    [2716.4s]       76000000 / 85814607 (0.9 %):    VIRT: 15053 MB  RSS: 14913MB
    [2751.6s]       77000000 / 85814607 (0.9 %):    VIRT: 15231 MB  RSS: 15090MB
    [2786.3s]       78000000 / 85814607 (0.9 %):    VIRT: 15379 MB  RSS: 15238MB
    [2820.1s]       79000000 / 85814607 (0.9 %):    VIRT: 15544 MB  RSS: 15403MB
    [2854.5s]       80000000 / 85814607 (0.9 %):    VIRT: 15695 MB  RSS: 15554MB
    [2887.4s]       81000000 / 85814607 (0.9 %):    VIRT: 15724 MB  RSS: 15584MB
    [2919.8s]       82000000 / 85814607 (1.0 %):    VIRT: 15724 MB  RSS: 15584MB
    [2953.8s]       83000000 / 85814607 (1.0 %):    VIRT: 15764 MB  RSS: 15623MB
    [2988.0s]       84000000 / 85814607 (1.0 %):    VIRT: 15834 MB  RSS: 15693MB
    [3021.9s]       85000000 / 85814607 (1.0 %):    VIRT: 15911 MB  RSS: 15771MB
    [3056.3s]       graph:  VIRT: 15948 MB  RSS: 15807MB
    # verifying reachability ...
    Traceback (most recent call last):
      File "fsrefs.py", line 235, in <module>
        main()
      File "fsrefs.py", line 232, in main
        missing.report()
      File "fsrefs.py", line 219, in report
        report(self.oid, self.data, self.serial, self.missing)
      File "fsrefs.py", line 83, in report
        from_mod, from_class = get_pickle_metadata(data)
      File "/srv/slapgrid/slappart7/srv/runner/kirr/ZODB/src/ZODB/utils.py", line 210, in get_pickle_metadata
        if data[0] in (0x80,    # Py3k indexes bytes -> int
    TypeError: 'NoneType' object has no attribute '__getitem__'