doc/requirements: Require pygments < 2.6 on py2
Commit 75c703fc (Security fix documentation dependencies (#342)) changed
requirements for pygments from

    # pygments 2.6 stops the support for python2
    pygments<2.6

to

    # Silence dependabot claiming a security issue in older versions:
    pygments >= 2.7.4

However this broke CI for python2, as sphinx now fails to install:

    Collecting Sphinx
      Using cached Sphinx-1.8.5-py2.py3-none-any.whl (3.1 MB)
    ERROR: Could not find a version that satisfies the requirement pygments>=2.7.4 (from -r doc/requirements.txt (line 3)) (from versions: 0.5, 0.5.1, 0.6, 0.7, 0.7.1, 0.8, 0.8.1, 0.9, 0.10, 0.11, 0.11.1, 1.0, 1.1, 1.1.1, 1.2, 1.2.1, 1.2.2, 1.3, 1.3.1, 1.4, 1.5, 1.6rc1, 1.6, 2.0rc1, 2.0, 2.0.1, 2.0.2, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.5.1, 2.5.2)
    ERROR: No matching distribution found for pygments>=2.7.4 (from -r doc/requirements.txt (line 3))
    The command "if [[ $TRAVIS_PYTHON_VERSION != pypy3* ]]; then pip install --upgrade --requirement doc/requirements.txt; fi" exited with 1.

(see e.g. https://travis-ci.com/github/zopefoundation/ZODB/jobs/499836548)

Try to fix that by bringing back requirement for `pygments < 2.6` on
python2.