More changes to get reusing savepoints working.
The tail end of testConnectionSavepoint.txt fails now.  This
is new test code, and the failure is pretty dreadful:

File "src\ZODB\tests\testConnectionSavepoint.txt", line 179, in testConnectionSavepoint.txt
Failed example:
    root['bob-balance']
Exception raised:
    Traceback (most recent call last):
      File "src\zope\testing\doctest.py", line 1256, in __run
        compileflags, 1) in test.globs
      File "<doctest testConnectionSavepoint.txt[48]>", line 1, in ?
        root['bob-balance']
      File "C:\python23\lib\UserDict.py", line 19, in __getitem__
        def __getitem__(self, key): return self.data[key]
      File "src\ZODB\Connection.py", line 704, in setstate
        self._setstate(obj)
      File "src\ZODB\Connection.py", line 742, in _setstate
        p, serial = self._storage.load(obj._p_oid, self._version)
      File "src\ZODB\Connection.py", line 1149, in load
        oidlen = u64(h)
      File "src\ZODB\utils.py", line 74, in u64
        return unpack(">Q", v)[0]
    error: unpack str size does not match format