scripts/netspace: Fix so it runs
Currently that script does not run because of import error:

    $ python src/ZODB/scripts/netspace.py
    Traceback (most recent call last):
      File "src/ZODB/scripts/netspace.py", line 13, in <module>
        from ZODB.referencesf import referencesf
    ImportError: No module named referencesf

and that ZODB.referencesf module was moved to ZODB.serialize long ago in

    ec014812    (Move referencesf to ZODB.serialize.)
    ae7e113e    (Ack!  Deleted the wrong file in the last checkin.)
    355ff4ac    (One more try.  Commit the version with referencesf.)

only the conversion missed the netspace.py script.

Fix it.