buildout: Fix Sphinx install on Python2
Else it is failing as:

    Got j1m.sphinxautozconfig 0.1.0.
    Getting distribution for 'sphinx_rtd_theme'.
    Got sphinx-rtd-theme 0.5.2.
    Version and requirements information containing docutils:
      Base installation request: 'Sphinx', 'docutils', 'ZODB', 'sphinxcontrib_zopeext', 'j1m.sphinxautozconfig', 'sphinx_rtd_theme'
      Requirement of sphinx_rtd_theme: docutils<0.17
      Requirement of j1m.sphinxautozconfig: docutils
      Requirement of Sphinx: docutils<0.17,>=0.12
    While:
      Installing sphinx.
    Error: There is a version conflict.
    We already have: docutils 0.17.1
    but sphinx-rtd-theme 0.5.2 requires 'docutils<0.17'.

(see e.g. https://travis-ci.com/github/zopefoundation/ZODB/jobs/499760337)

Suggested by @d-maurer.